name: Continuous integration
on: [push]
jobs:
  test-nixpkgs:
    name: Build & Test - Nixpkgs
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14.1
        with:
          nix_path: nixpkgs=./nixpkgs.nix
      - name: Configure
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
        run: |
          cat >.bazelrc.local <<EOF
          common --config=ci
          build --remote_header=x-buildbuddy-api-key="$BUILDBUDDY_API_KEY"
          EOF
      - name: Build & test
        run: |
          nix-shell --pure --run '
            set -euo pipefail
            bazel test //...
          '
          for dir in $PWD/examples/toolchains/*; do
              cd "$dir"
              nix-shell --command 'bazel run --config=nix :hello'
          done
